### ISSUE TITLE
No comments in such simple code

### ISSUE THREAD

**Issue by white-collar** [alex-s93/java_homeworks#3]
https://github.com/alex-s93/java_homeworks/blob/a5cf6132e4652a30c14bd129ebcbf621d9aa6b23/com/alevel/homework3/task2/ArithmeticAverage.java#L5

Please never use comments in such simple code, it adds extra details and code which you are writing for must be self-comprehensible. Only on really difficult cases comments are pertinent.

**Comment by alex-s93** [comment]
Removed comments from simple code
